---

inherit_from:
  - ".rubocop_disabled.yml"

require:
- rubocop-capybara
- rubocop-rails
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
  - 'bin/**/*'
  - 'coverage/**/*'
  - 'lib/s2/messages/**/*' # Generated code
  - 'tmp/**/*'
  - 'vendor/**/*'

Rails:
  Enabled: true

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button

Layout/BeginEndAlignment:
  Enabled: true

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/ClassStructure:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: true
  Max: 115
  Exclude:
  - app/views/prometheus/*.erb

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  Exclude:
  - spec/**/*

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessAssignment:
  Exclude:
  - spec/**/*

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Metrics/AbcSize:
  Exclude:
  - spec/components/previews/**/*

Metrics/BlockLength:
  AllowedMethods:
  - class_methods
  - included
  - class_operations
  - class_queries
  - instance_operations
  - instance_queries
  Exclude:
  - "**/spec/**/*"
  - config/routes.rb
  - config/initializers/**/*.rb
  - "**/*.gemspec"
  - config/environments/**/*
  - lib/tasks/**/*.rake

Metrics/CyclomaticComplexity:
  Max: 42

Metrics/MethodLength:
  Max: 42
  Exclude:
  - "**/spec/**/*"

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 42

Naming/AccessorMethodName:
  Exclude:
  - app/models/**/*.rb

Naming/FileName:
  Exclude:
    - lib/s2-ruby.rb

Naming/MethodParameterName:
  MinNameLength: 2

Naming/PredicateName:
  Enabled: true
  ForbiddenPrefixes: [is_]

Naming/VariableNumber:
  Enabled: true
  Exclude:
  - spec/**/*
  - gems/we_connect/spec//**/*

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Exclude:
  - spec/domain/**/*

RSpec/VerifiedDoubles:
  Enabled: true
  Exclude:
  - spec/components/previews/**/*

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/EnvironmentVariableAccess:
  AllowReads: true

Rails/Exit:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true
  Include:
  - "**/*.rb"
  - "**/*.erb"

Rails/I18nLocaleTexts:
  Exclude:
  - app/controllers/admin/**/*

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
  AllowedMethods:
  - upsert

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true
  Include:
  - "**/*.rb"
  - "**/*.erb"

Rails/UnknownEnv:
  Environments:
  - development
  - local
  - production
  - staging
  - test

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true
  AllowedReceivers:
  - event

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/OptionalBooleanParameter:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Exclude:
  - spec/**/*

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
