require:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: "3.4"
  Exclude:
    - bin/**/*
    - vendor/**/*
    - lib/s2/messages.rb

Metrics/ClassLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 115

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/spec/**/*"

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/UselessAssignment:
  Exclude:
    - "**/spec/**/*"

Metrics/BlockLength:
  AllowedMethods:
    - class_methods
    - included
  Exclude:
    - "**/spec/**/*"
    - "**/*.gemspec"

Metrics/CyclomaticComplexity:
  Max: 42

Metrics/MethodLength:
  Max: 42
  Exclude:
    - "**/spec/**/*"

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 42

Naming/MethodParameterName:
  MinNameLength: 2

Naming/PredicatePrefix:
  ForbiddenPrefixes:
    - is_

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/NestedGroups:
  Max: 4

RSpec/VerifiedDoubles:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Lambda:
  EnforcedStyle: literal

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Exclude:
    - "**/spec/**/*"

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
